services:
  db:
    image: postgres:16
    container_name: local_pgdb
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: charbel
      POSTGRES_PASSWORD: charbel
      POSTGRES_DB: matching_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: charbeldaher34@gmail.com
      PGADMIN_DEFAULT_PASSWORD: charbel
    volumes:
      - pgadmin-data:/var/lib/pgadmin
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: backend
    restart: always
    ports: 
      - "8017:8017"
    depends_on:
      - db
    environment:
      - POSTGRES_USER=app_user
      - POSTGRES_PASSWORD=a
      - POSTGRES_DB=matching_db
      - POSTGRES_PORT=5437
      - POSTGRES_HOST=db
      - POSTGRES_HOST_AUTH_METHOD=trust
      - ai_url=http://ai:8011
      - GEMINI_API_KEY=AIzaSyDp8n_AmYsspADJBaNpkJvBdlch1-9vkhw
      - LOGFIRE_TOKEN=pylf_v1_us_659r32Hx0CWSbpJFLL6R0xhwm3N1Xjxq99DqYSJBpQWN
      # Email configuration (replace with your SMTP settings)
      - SMTP_HOST=smtp.gmail.com
      - SMTP_PORT=587
      - SMTP_USERNAME=charbeldaher34@gmail.com
      - SMTP_PASSWORD=dqfp axar sozd qkps
      - FROM_EMAIL=charbeldaher34@gmail.com
      # OTP configuration
      - OTP_EXPIRE_MINUTES=10
      - OTP_LENGTH=6
  ai:
    build:
      context: ./ai
      dockerfile: Dockerfile
    container_name: ai
    restart: always
    ports: 
      - "8011:8011"
    environment:
      - API_KEY=AIzaSyDp8n_AmYsspADJBaNpkJvBdlch1-9vkhw
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
    container_name: frontend
    restart: always
    ports: 
      - "8080:8080"
    depends_on:
      - backend
      - db
    environment:
      - VITE_DOCKER=true
    
volumes:
  local_pgdata:
  pgadmin-data: