"""f

Revision ID: 08b01fb7d771
Revises: f4d8159e52d1
Create Date: 2025-06-03 09:29:46.645207

"""

from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = "08b01fb7d771"
down_revision: Union[str, None] = "f4d8159e52d1"
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column("match", "candidate")
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column(
        "match",
        sa.Column("candidate", sa.VARCHAR(), autoincrement=False, nullable=True),
    )
    # ### end Alembic commands ###
