""".

Revision ID: 2025fc1f4e83
Revises: 79f65d031014
Create Date: 2025-05-28 08:31:07.729568

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '2025fc1f4e83'
down_revision: Union[str, None] = '79f65d031014'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('company', sa.Column('domain', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('hr', sa.Column('password', sqlmodel.sql.sqltypes.AutoString(), nullable=False))
    op.drop_column('hr', 'password_hash')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('hr', sa.Column('password_hash', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('hr', 'password')
    op.drop_column('company', 'domain')
    # ### end Alembic commands ###
