"""assign required fields

Revision ID: 232b12738a59
Revises: 6143e3f55305
Create Date: 2025-05-23 10:22:34.279935

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '232b12738a59'
down_revision: Union[str, None] = '6143e3f55305'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'candidate', ['email'])
    op.create_unique_constraint(None, 'candidate', ['phone'])
    op.create_unique_constraint(None, 'company', ['website'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'company', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    op.drop_constraint(None, 'candidate', type_='unique')
    # ### end Alembic commands ###
