"""f

Revision ID: 49b5f4b40e12
Revises: 
Create Date: 2025-06-03 07:28:38.324178

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = '49b5f4b40e12'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('candidate', sqlmodel.sql.sqltypes.AutoString(), nullable=True))
    op.add_column('match', sa.Column('score', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('embedding_similarity', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('match_percentage', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('matching_skills', sa.JSON(), nullable=True))
    op.add_column('match', sa.Column('missing_skills', sa.JSON(), nullable=True))
    op.add_column('match', sa.Column('extra_skills', sa.JSON(), nullable=True))
    op.add_column('match', sa.Column('total_required_skills', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('matching_skills_count', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('missing_skills_count', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('extra_skills_count', sa.Integer(), nullable=True))
    op.add_column('match', sa.Column('skill_weight', sa.Float(), nullable=True))
    op.add_column('match', sa.Column('embedding_weight', sa.Float(), nullable=True))
    op.drop_column('match', 'match_result')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('match_result', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('match', 'embedding_weight')
    op.drop_column('match', 'skill_weight')
    op.drop_column('match', 'extra_skills_count')
    op.drop_column('match', 'missing_skills_count')
    op.drop_column('match', 'matching_skills_count')
    op.drop_column('match', 'total_required_skills')
    op.drop_column('match', 'extra_skills')
    op.drop_column('match', 'missing_skills')
    op.drop_column('match', 'matching_skills')
    op.drop_column('match', 'match_percentage')
    op.drop_column('match', 'embedding_similarity')
    op.drop_column('match', 'score')
    op.drop_column('match', 'candidate')
    # ### end Alembic commands ###
