"""add employer id for candidate

Revision ID: 559c8ac730d4
Revises: e7aa5cf3735d
Create Date: 2025-06-02 07:52:05.090937

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '559c8ac730d4'
down_revision: Union[str, None] = 'e7aa5cf3735d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('candidate', sa.Column('employer_id', sa.Integer(), nullable=True))
    op.create_foreign_key(None, 'candidate', 'company', ['employer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'candidate', type_='foreignkey')
    op.drop_column('candidate', 'employer_id')
    # ### end Alembic commands ###
