"""change the interview table types

Revision ID: 6aff9a3d25bd
Revises: 559c8ac730d4
Create Date: 2025-06-02 09:42:57.715350

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '6aff9a3d25bd'
down_revision: Union[str, None] = '559c8ac730d4'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview', 'type',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('PHONE', 'ONLINE', 'IN_PERSON', name='interviewtype_enum'),
               nullable=True)
    op.alter_column('interview', 'status',
               existing_type=sa.VARCHAR(),
               type_=sa.Enum('SCHEDULED', 'DONE', 'CANCELED', name='interviewstatus_enum'),
               nullable=True)
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('interview', 'status',
               existing_type=sa.Enum('SCHEDULED', 'DONE', 'CANCELED', name='interviewstatus_enum'),
               type_=sa.VARCHAR(),
               nullable=False)
    op.alter_column('interview', 'type',
               existing_type=sa.Enum('PHONE', 'ONLINE', 'IN_PERSON', name='interviewtype_enum'),
               type_=sa.VARCHAR(),
               nullable=False)
    # ### end Alembic commands ###
