"""seperate base model and table

Revision ID: 7473cc497ab6
Revises: 3c6f6e830ad0
Create Date: 2025-05-23 10:47:44.514450

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '7473cc497ab6'
down_revision: Union[str, None] = '3c6f6e830ad0'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('company', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=False)
    op.drop_constraint(op.f('company_website_key'), 'company', type_='unique')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(op.f('company_website_key'), 'company', ['website'], postgresql_nulls_not_distinct=False)
    op.alter_column('company', 'is_owner',
               existing_type=sa.BOOLEAN(),
               nullable=True)
    # ### end Alembic commands ###
