"""chagne the match base model into a json data

Revision ID: 79f65d031014
Revises: 7e208e325b64
Create Date: 2025-05-25 14:46:23.054064

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = '79f65d031014'
down_revision: Union[str, None] = '7e208e325b64'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('match_result', sa.JSON(), nullable=True))
    op.drop_column('match', 'match_score')
    op.drop_column('match', 'attribute_scores')
    op.drop_column('match', 'skills_report')
    op.drop_column('match', 'narrative_explanation')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('narrative_explanation', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('skills_report', sa.TEXT(), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('attribute_scores', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.add_column('match', sa.Column('match_score', sa.DOUBLE_PRECISION(precision=53), autoincrement=False, nullable=False))
    op.drop_column('match', 'match_result')
    # ### end Alembic commands ###
