"""change the db

Revision ID: a88e5c05bd06
Revises: 32e8f06b31d9
Create Date: 2025-05-23 10:18:19.360824

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql
import sqlmodel

# revision identifiers, used by Alembic.
revision: str = 'a88e5c05bd06'
down_revision: Union[str, None] = '32e8f06b31d9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('application', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('application', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('application', 'submitted_at')
    op.add_column('candidate', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.alter_column('company', 'description',
               existing_type=sa.TEXT(),
               type_=sqlmodel.sql.sqltypes.AutoString(),
               existing_nullable=True)
    op.drop_index(op.f('ix_company_name'), table_name='company')
    op.add_column('formkey', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.drop_column('job', 'form_key_ids')
    op.add_column('jobformkeyconstraint', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('jobformkeyconstraint', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('match', sa.Column('created_at', sa.DateTime(), nullable=False))
    op.add_column('match', sa.Column('updated_at', sa.DateTime(), nullable=False))
    op.add_column('recruitercompanylink', sa.Column('updated_at', sa.DateTime(), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('recruitercompanylink', 'updated_at')
    op.drop_column('match', 'updated_at')
    op.drop_column('match', 'created_at')
    op.drop_column('jobformkeyconstraint', 'updated_at')
    op.drop_column('jobformkeyconstraint', 'created_at')
    op.add_column('job', sa.Column('form_key_ids', postgresql.JSON(astext_type=sa.Text()), autoincrement=False, nullable=True))
    op.drop_column('formkey', 'updated_at')
    op.create_index(op.f('ix_company_name'), 'company', ['name'], unique=True)
    op.alter_column('company', 'description',
               existing_type=sqlmodel.sql.sqltypes.AutoString(),
               type_=sa.TEXT(),
               existing_nullable=True)
    op.drop_column('candidate', 'updated_at')
    op.add_column('application', sa.Column('submitted_at', postgresql.TIMESTAMP(), autoincrement=False, nullable=False))
    op.drop_column('application', 'updated_at')
    op.drop_column('application', 'created_at')
    # ### end Alembic commands ###
