"""add constraints per form key for each job

Revision ID: b1fa7664b42c
Revises: c9df5dc322bc
Create Date: 2025-05-23 08:37:36.974355

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'b1fa7664b42c'
down_revision: Union[str, None] = 'c9df5dc322bc'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('jobformkeyconstraint',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('job_id', sa.Integer(), nullable=False),
    sa.Column('form_key_id', sa.Integer(), nullable=False),
    sa.Column('constraints', sa.JSON(), nullable=True),
    sa.ForeignKeyConstraint(['form_key_id'], ['formkey.id'], ),
    sa.ForeignKeyConstraint(['job_id'], ['job.id'], ),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('jobformkeyconstraint')
    # ### end Alembic commands ###
