"""add enum values for enum types

Revision ID: c6857cc1a119
Revises: b1fa7664b42c
Create Date: 2025-05-23 08:43:11.198405

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c6857cc1a119'
down_revision: Union[str, None] = 'b1fa7664b42c'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('formkey', sa.Column('enum_values', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('formkey', 'enum_values')
    # ### end Alembic commands ###
