"""connect match to job and candidate only through application

Revision ID: c9df5dc322bc
Revises: fcfd91f7084a
Create Date: 2025-05-23 07:17:39.149763

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c9df5dc322bc'
down_revision: Union[str, None] = 'fcfd91f7084a'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('application_id', sa.Integer(), nullable=False))
    op.drop_constraint(op.f('match_job_id_fkey'), 'match', type_='foreignkey')
    op.drop_constraint(op.f('match_candidate_id_fkey'), 'match', type_='foreignkey')
    op.create_foreign_key(None, 'match', 'application', ['application_id'], ['id'])
    op.drop_column('match', 'job_id')
    op.drop_column('match', 'candidate_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('match', sa.Column('candidate_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.add_column('match', sa.Column('job_id', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'match', type_='foreignkey')
    op.create_foreign_key(op.f('match_candidate_id_fkey'), 'match', 'candidate', ['candidate_id'], ['id'])
    op.create_foreign_key(op.f('match_job_id_fkey'), 'match', 'job', ['job_id'], ['id'])
    op.drop_column('match', 'application_id')
    # ### end Alembic commands ###
