"""add list of questions for a job

Revision ID: de714ad92a08
Revises: bb8263755adb
Create Date: 2025-07-04 10:01:12.887004

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'de714ad92a08'
down_revision: Union[str, None] = 'bb8263755adb'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('job', sa.Column('tailored_questions', sa.JSON(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('job', 'tailored_questions')
    # ### end Alembic commands ###
