version: "3.8"
services:
  db:
    image: postgres
    container_name: local_pgdb
    restart: always
    ports:
      - "5437:5432"
    environment:
      POSTGRES_USER: charbel
      POSTGRES_PASSWORD: charbel
      POSTGRES_DB: matching_db
    volumes:
      - local_pgdata:/var/lib/postgresql/data
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
  pgadmin:
    image: dpage/pgadmin4
    container_name: pgadmin4_container
    restart: always
    ports:
      - "8888:80"
    environment:
      PGADMIN_DEFAULT_EMAIL: charbeldaher34@gmail.com
      PGADMIN_DEFAULT_PASSWORD: charbel
    volumes:
      - pgadmin-data:/var/lib/pgadmin

volumes:
  local_pgdata:
  pgadmin-data: