apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: ai-pvc
  namespace: recruitment-app
  labels:
    app: ai-service
spec:
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
