apiVersion: apps/v1
kind: Deployment
metadata:
  name: ai-deployment
  namespace: recruitment-app
  labels:
    app: ai-service
spec:
  replicas: 1
  selector:
    matchLabels:
      app: ai-service
  template:
    metadata:
      labels:
        app: ai-service
    spec:
      containers:
        - name: ai-container
          image: matching-ai:local # Update with your actual image
          imagePullPolicy: Never
          ports:
            - containerPort: 8011
          env:
            - name: API_KEY
              valueFrom:
                secretKeyRef:
                  name: ai-secret
                  key: API_KEY
          volumeMounts:
            - mountPath: /app/static
              name: ai-storage
          livenessProbe:
            httpGet:
              path: /
              port: 8011
            initialDelaySeconds: 30
            periodSeconds: 15
          readinessProbe:
            httpGet:
              path: /
              port: 8011
            initialDelaySeconds: 10
            periodSeconds: 10
          resources:
            requests:
              memory: "1Gi"
              cpu: "250m"
            limits:
              memory: "2Gi"
              cpu: "1000m"
      volumes:
        - name: ai-storage
          persistentVolumeClaim:
            claimName: ai-pvc
