apiVersion: v1
kind: Service
metadata:
  name: backend-service
  namespace: recruitment-app
  labels:
    app: backend-service
spec:
  ports:
    - name: backend
      port: 8017
      targetPort: 8017
  selector:
    app: backend-service
  type: ClusterIP  # Keep as ClusterIP for internal cluster access only
