apiVersion: v1
kind: ConfigMap
metadata:
  name: backend-configmap
  namespace: recruitment-app
data:
  POSTGRES_DB: "matching_db"
  POSTGRES_HOST: "postgres-service.recruitment-app.svc.cluster.local"
  POSTGRES_SERVER: "postgres-service.recruitment-app.svc.cluster.local"
  POSTGRES_PORT: "5432"
  POSTGRES_HOST_AUTH_METHOD: "trust"
  AI_URL: "http://ai-service.recruitment-app.svc.cluster.local:8011"
  AI_PORT: "8011"
  SMTP_HOST: "smtp.gmail.com"
  SMTP_PORT: "587"
  SMTP_USERNAME: "charbeldaher34@gmail.com"
  FROM_EMAIL: "charbeldaher34@gmail.com"
  OTP_EXPIRE_MINUTES: "10"
  OTP_LENGTH: "6"
---
apiVersion: v1
kind: ConfigMap
metadata:
  name: frontend-configmap
  namespace: recruitment-app
data:
  PROXY_PASS_URL: "backend-service.recruitment-app.svc.cluster.local:8017"
  NODE_ENV: "production"

# Frontend now uses nginx proxy - no VITE_API_URL needed
# API requests are proxied by nginx to the backend service 