apiVersion: v1
kind: Secret
metadata:
  name: postgres-secret
  namespace: recruitment-app
type: Opaque
data:
  POSTGRES_USER: Y2hhcmJlbA== # "charbel" base64 encoded
  POSTGRES_PASSWORD: Y2hhcmJlbA== # "charbel" base64 encoded
  APP_DB_USER: YXBwX3VzZXI= # "app_user" base64 encoded
  APP_DB_PASS: YQ== # "a" base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: backend-secret
  namespace: recruitment-app
type: Opaque
data:
  GEMINI_API_KEY: QUl6YVN5RHA4bl9BbVlzc3BBREpCYU5wa0p2QmRsY2gxLTl2a2h3 # base64 encoded
  LOGFIRE_TOKEN: cHlsZl92MV91c182NTlyMzJIeDBDV1NicEpGTEw2UjB4aHdtM04xWGp4cTk5RHFZU0pCcFFXTg== # base64 encoded
  SMTP_PASSWORD: ZHFmcCBheGFyIHNvemQgcWtwcw== # "dqfp axar sozd qkps" base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: ai-secret
  namespace: recruitment-app
type: Opaque
data:
  API_KEY: QUl6YVN5RHA4bl9BbVlzc3BBREpCYU5wa0p2QmRsY2gxLTl2a2h3 # base64 encoded
---
apiVersion: v1
kind: Secret
metadata:
  name: pgadmin-secret
  namespace: recruitment-app
type: Opaque
data:
  PGADMIN_DEFAULT_EMAIL: Y2hhcmJlbGRhaGVyMzRAZ21haWwuY29t # base64 encoded
  PGADMIN_DEFAULT_PASSWORD: Y2hhcmJlbA== # "charbel" base64 encoded 